### ISSUE TITLE
Allow Access to Sites

### ISSUE THREAD

**Issue by CodeMouse92** [bomsn/my-canned-responses#1]
I want to be able to use this on GitHub, DEV, and a few other places where I do community management. Right now, I'm copying everything, but it would be easier to just click Add.

To do that, I have to be able to grant access to the site to the extension, but there's no way to do that.

Can you add support for that?

**Comment by bomsn** [comment]
We can add such option, but we'd still need to figure out where to "Add" exactly via CSS selectors ..etc and there is no way to do this automatically as the text could drop in the wrong place.

This is how we add the responses to Google for example:

        textArea = document.querySelectorAll('[contenteditable].editable');

        if (typeof (textArea) != 'undefined' && textArea != null && textArea != '' && textArea.length > 0) {

          let cannedReply = document.createElement("div"),
            lastTextArea = textArea[textArea.length - 1],
            gmailQuote = lastTextArea.querySelectorAll('.gmail_quote');

          // Assign the reply to an element
          cannedReply.innerHTML = request.message;

          if (gmailQuote.length > 0) {
            lastTextArea.insertBefore(cannedReply, gmailQuote[0])
          } else {
            lastTextArea.appendChild(cannedReply);
          }

          added = true;
        }

and it's a slightly different process for Outlook, and other sites. Hope this explains why we can't create the option to just add a website. However, I'm happy to add support to new websites if you could share a list with me.

**Comment by CodeMouse92** [comment]
Ahh, makes sense.

At the moment, GitHub is probably the main place I need this, specifically the comment box on Issues and PRs.

**Comment by bomsn** [comment]
Perfect, I'll update shortly.

**Comment by bomsn** [comment]
Done, I've added support to Github, Stackoverflow and Upwork. I've published the update to Chrome web store, but it'll probably take some time before being available.
